// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKbcC2M3HigydZWZZaRxh8EISKu0m4uZc',
    appId: '1:83821217953:web:e6a6d439c4ae747b7e08e0',
    messagingSenderId: '83821217953',
    projectId: 'bloodbankppa-cd626',
    authDomain: 'bloodbankppa-cd626.firebaseapp.com',
    storageBucket: 'bloodbankppa-cd626.appspot.com',
    measurementId: 'G-JSLWJT4W3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqAt62jiVabj2DLtuID2oQH0gFvWWbr1g',
    appId: '1:83821217953:android:78f6f540f9d07fe37e08e0',
    messagingSenderId: '83821217953',
    projectId: 'bloodbankppa-cd626',
    storageBucket: 'bloodbankppa-cd626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOz68NYmSZO5EZAP08PsUyDHjtJ_jj9c',
    appId: '1:83821217953:ios:8dd0a1ff8cd1699a7e08e0',
    messagingSenderId: '83821217953',
    projectId: 'bloodbankppa-cd626',
    storageBucket: 'bloodbankppa-cd626.appspot.com',
    iosClientId: '83821217953-mke7kmcjbhe8ss1r08bc7ht4e95hih7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodbankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBOz68NYmSZO5EZAP08PsUyDHjtJ_jj9c',
    appId: '1:83821217953:ios:8dd0a1ff8cd1699a7e08e0',
    messagingSenderId: '83821217953',
    projectId: 'bloodbankppa-cd626',
    storageBucket: 'bloodbankppa-cd626.appspot.com',
    iosClientId: '83821217953-mke7kmcjbhe8ss1r08bc7ht4e95hih7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodbankApp',
  );
}
